apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-interview
resources:
  - ../../base

images:
  - name: BACKEND_IMAGE
    newName: 000000000000.dkr.ecr.ap-south-1.amazonaws.com/webrtc-assistance/backend
    newTag: latest
  - name: FRONTEND_IMAGE
    newName: 000000000000.dkr.ecr.ap-south-1.amazonaws.com/webrtc-assistance/frontend
    newTag: latest
