apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webrtc-assistance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/neutron420/webrtc-assistance.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-interview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
