apiVersion: v1
kind: Service
metadata:
  name: interview-redis
  namespace: ai-interview
spec:
  selector:
    app: interview-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP
